#!/usr/bin/env bash
# This script will display "Best School" 8 times at the 4 position it will display "bad luck" and at the 8 position it will display "good luck"


counter=1
while [ $counter -le 10 ]
do 
    if [ $counter == '4' ]
    then
    echo "bad luck"
    elif [ $counter == '8' ]
    then
    echo "good luck"
    else
    echo "Best School"
    fi
   ((counter++))
done    

